//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C56rms_file> C56rms_file { get; set; }
        public DbSet<C56rms_group> C56rms_group { get; set; }
        public DbSet<C56rms_inform_table> C56rms_inform_table { get; set; }
        public DbSet<C56rms_limit> C56rms_limit { get; set; }
        public DbSet<C56rms_user> C56rms_user { get; set; }
        public DbSet<C56rms_user_role> C56rms_user_role { get; set; }
    }
}
