//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class C56rms_user
    {
        public C56rms_user()
        {
            this.C56rms_file = new HashSet<C56rms_file>();
        }
    
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string user_gender { get; set; }
        public Nullable<int> user_grade { get; set; }
        public Nullable<int> user_department { get; set; }
        public Nullable<int> user_major { get; set; }
        public Nullable<long> user_tel { get; set; }
        public Nullable<long> user_qq { get; set; }
        public string user_email { get; set; }
        public string user_psw_quest { get; set; }
        public string user_psw_answ { get; set; }
        public int user_limit { get; set; }
        public string user_realname { get; set; }
    
        public virtual ICollection<C56rms_file> C56rms_file { get; set; }
        public virtual C56rms_group C56rms_group { get; set; }
        public virtual C56rms_inform_table C56rms_inform_table { get; set; }
        public virtual C56rms_user_role C56rms_user_role { get; set; }
    }
}
