//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class C56rms_inform_table
    {
        public int inform_user_id { get; set; }
        public string inform_title { get; set; }
        public string inform_content { get; set; }
        public System.DateTime inform_pu_time { get; set; }
    
        public virtual C56rms_user C56rms_user { get; set; }
    }
}
